# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jgiron <jgiron@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/19 07:10:46 by jgiron            #+#    #+#              #
#    Updated: 2022/04/19 07:11:04 by jgiron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


SRCS    = yyerror.c \
			main.c

NAME    =	liby.a

SRCS_DIR = srcs

OBJS_DIR = .objs

INCLUDE_DIR = .

CFLAGS = -Wall -Werror -Wextra -g3

include lib.mk